//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdEntities : DbContext
    {
        public bdEntities()
            : base("name=bdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actividades> actividades { get; set; }
        public virtual DbSet<administradores> administradores { get; set; }
        public virtual DbSet<comites> comites { get; set; }
        public virtual DbSet<domicilios> domicilios { get; set; }
        public virtual DbSet<empresas> empresas { get; set; }
        public virtual DbSet<facturacion> facturacion { get; set; }
        public virtual DbSet<normas> normas { get; set; }
        public virtual DbSet<organizaciones> organizaciones { get; set; }
        public virtual DbSet<profesiones> profesiones { get; set; }
        public virtual DbSet<puestos> puestos { get; set; }
        public virtual DbSet<responsables> responsables { get; set; }
        public virtual DbSet<sitios> sitios { get; set; }
        public virtual DbSet<telefonos> telefonos { get; set; }
        public virtual DbSet<temas> temas { get; set; }
        public virtual DbSet<empresa_norma> empresa_norma { get; set; }
        public virtual DbSet<empresa_organizacion> empresa_organizacion { get; set; }
        public virtual DbSet<empresa_tema> empresa_tema { get; set; }
    }
}
