//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalles_empresa
    {
        public int id_detalles_empresa { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> productos { get; set; }
        public Nullable<bool> servicios { get; set; }
        public Nullable<int> numero_empleados { get; set; }
        public Nullable<int> id_facturacion { get; set; }
        public Nullable<bool> exporta { get; set; }
        public Nullable<bool> en_proceso_exportacion { get; set; }
        public string paises_exportacion { get; set; }
        public string sugerencia { get; set; }
    }
}
