//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresas
    {
        public int id_empresa { get; set; }
        public string razon_social { get; set; }
        public string rfc { get; set; }
        public string nombre_comercial { get; set; }
        public Nullable<bool> solicitud_aceptada { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<bool> baja { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
        public Nullable<System.DateTime> fecha_solicitud { get; set; }
        public Nullable<bool> solicitud_rechazada { get; set; }
        public Nullable<int> id_causa_baja { get; set; }
        public string comentario_baja { get; set; }
        public string codigo_empresa { get; set; }
        public string comentario_aceptado { get; set; }
    }
}
