//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class bdEntities : DbContext
    {
        public bdEntities()
            : base("name=bdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<administradores> administradores { get; set; }
        public virtual DbSet<cadena_productiva> cadena_productiva { get; set; }
        public virtual DbSet<comites> comites { get; set; }
        public virtual DbSet<detalles_empresa> detalles_empresa { get; set; }
        public virtual DbSet<domicilios> domicilios { get; set; }
        public virtual DbSet<empresa_cadena_productiva> empresa_cadena_productiva { get; set; }
        public virtual DbSet<empresa_norma> empresa_norma { get; set; }
        public virtual DbSet<empresa_organizacion> empresa_organizacion { get; set; }
        public virtual DbSet<empresa_tema> empresa_tema { get; set; }
        public virtual DbSet<facturacion> facturacion { get; set; }
        public virtual DbSet<normas> normas { get; set; }
        public virtual DbSet<organizaciones> organizaciones { get; set; }
        public virtual DbSet<profesiones> profesiones { get; set; }
        public virtual DbSet<puestos> puestos { get; set; }
        public virtual DbSet<requisitos> requisitos { get; set; }
        public virtual DbSet<responsables> responsables { get; set; }
        public virtual DbSet<sitios> sitios { get; set; }
        public virtual DbSet<telefonos> telefonos { get; set; }
        public virtual DbSet<temas> temas { get; set; }
        public virtual DbSet<responsables_cluster_view> responsables_cluster_view { get; set; }
        public virtual DbSet<responsables_comites_view> responsables_comites_view { get; set; }
        public virtual DbSet<cadena_productiva_view> cadena_productiva_view { get; set; }
        public virtual DbSet<empresa_norma_view> empresa_norma_view { get; set; }
        public virtual DbSet<empresa_tema_view> empresa_tema_view { get; set; }
        public virtual DbSet<empresas> empresas { get; set; }
    
        public virtual ObjectResult<sp_get_empresa_Result> sp_get_empresa(Nullable<int> pIdEmpresa)
        {
            var pIdEmpresaParameter = pIdEmpresa.HasValue ?
                new ObjectParameter("pIdEmpresa", pIdEmpresa) :
                new ObjectParameter("pIdEmpresa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_empresa_Result>("sp_get_empresa", pIdEmpresaParameter);
        }
    
        public virtual ObjectResult<sp_get_empresa_detalle_Result> sp_get_empresa_detalle(Nullable<int> pIdEmpresa)
        {
            var pIdEmpresaParameter = pIdEmpresa.HasValue ?
                new ObjectParameter("pIdEmpresa", pIdEmpresa) :
                new ObjectParameter("pIdEmpresa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_empresa_detalle_Result>("sp_get_empresa_detalle", pIdEmpresaParameter);
        }
    
        public virtual ObjectResult<sp_get_empresa_detalle_by_id_Result> sp_get_empresa_detalle_by_id(Nullable<int> pIdEmpresa)
        {
            var pIdEmpresaParameter = pIdEmpresa.HasValue ?
                new ObjectParameter("pIdEmpresa", pIdEmpresa) :
                new ObjectParameter("pIdEmpresa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_empresa_detalle_by_id_Result>("sp_get_empresa_detalle_by_id", pIdEmpresaParameter);
        }
    }
}
