//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class responsables_comites_view
    {
        public Nullable<int> id_empresa { get; set; }
        public int id_responsable { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string correo { get; set; }
        public string telefono_oficina { get; set; }
        public string telefono_whatsapp { get; set; }
        public string comite { get; set; }
        public string puesto { get; set; }
        public string profesion { get; set; }
    }
}
